let tooltips={
    0:{
        data_jbox_content:"&#8594; Doesn't need to be scanned<br>&#8594; Visible as <i>Unidentified Wormhole</i>"
    },
    1:{
        data_jbox_content:"&#8594; Can be <a>static</a> in C13 systems"
    },
    2:{
        data_jbox_content:"Every <span class='ns'>Pochven</span> system is always connected to this type.<br>&#8594; <i>Ships allowed:</i> up to Bowhead<br>&#8594; <i>Excluded:</i> all other Freighters<br>&#8594; <i>Unique jump size mass:</i> 410 000 000 kg"
    },
    3:{
        data_jbox_content:"&#8594; Is <a>static</a> only in one shattered <span class='C5'>C5</span> system; J011790"
    },
    4:{
        data_jbox_content:"&#8594; Can be <a>static</a> in shattered <span class='C4'>C4</span> systems"
    },
    5:{
        data_jbox_content:"&#8594; Can be <a>static</a> in shattered <span class='C4'>C4</span>, <span class='C5'>C5</span> and <span class='C6'>C6</span> systems"
    },
    6:{
        data_jbox_content:"&#8594; Can be <a>static</a> in shattered <span class='C4'>C4</span> and <span class='C5'>C5</span> systems"
    },
    7:{
        data_jbox_content:"Generic type designating an exit."
    },
    8:{
        data_jbox_content:"&#8594; <i>Regions & constellations:</i> A-"
    },
    9:{
        data_jbox_content:"&#8594; <i>Regions & constellations:</i> B-"
    },
    10:{
        data_jbox_content:"&#8594; <i>Regions & constellations:</i> C-"
    },
    11:{
        data_jbox_content:"&#8594; <i>Regions & constellations:</i> D-"
    },
    12:{
        data_jbox_content:"&#8594; <i>Regions & constellations:</i> E-"
    },
    13:{
        data_jbox_content:"&#8594; <i>Region & constellations:</i> F-"
    },
    14:{
        data_jbox_content:"Unique shattered wormhole system, and only one with a name.<br>Has 4 NPC stations belonging to <i>Sisters of EVE</i>.<br>&#8594; <i>Region & constellation:</i> G-"
    },
    15:{
        data_jbox_content:"25 shattered wormhole systems accessible only via 'frigate holes'.<br>&#8594; <i>System effect:</i> C6 Wolf Rayet<br>&#8594; <i>Anomalies:</i> C1-C3<br><i>&#8594; Jcode:</i> starts with 000<br>&#8594; <i>Region & constellations:</i> H-"
    },
    16:{
        data_jbox_content:"<i>NullSec regions:</i><br>&#8594; Cobalt Edge, Etherium Reach, Kalevala Expanse,<br>&#8594; Malpais, Oasa, Outer Passage, Perrigen Falls, The Spire"
    },
    17:{
        data_jbox_content:"5 unique shattered wormhole systems, each with its own class and system effect.<br>&#8594; <i>Region & constellations:</i> K-<br>&#8594; Class 14-18"
    },
    18:{
        data_jbox_content:"&#8594; These structures are located across <i>known space</i>.<br>&#8594; Referred wormhole types spawn only in systems having them.<br>&#8594; First letter in each type reveals the name of a <i>Drifter</i> system destination."
    },
    19:{
        data_jbox_content:"Bob knows why ..."
    },
    20:{
        data_jbox_content:"It's type originated on the other side."
    },
    21:{
        data_jbox_content:"&#8594; <i>Class:</i> C15<br>&#8594; NPC Faction: Minmatar<br>&#8594; <i>System effect:</i> C2 Cataclysmic Variable<br>&#8594; <i>Former Jcode:</i> J110145"
    },
    22:{
        data_jbox_content:"&#8594; <i>Class:</i> C16<br>&#8594; NPC Faction: Amarr<br><i>&#8594; System effect:</i> C2 Magnetar<br>&#8594; <i>Former Jcode:</i> J164710"
    },
    23:{
        data_jbox_content:"&#8594; <i>Class:</i> C17<br>&#8594; NPC Faction: Caldari<br><i>&#8594; System effect:</i> C2 Pulsar<br>&#8594; <i>Former Jcode:</i> J200727"
    },
    24:{
        data_jbox_content:"&#8594; <i>Class:</i> C18<br>&#8594; NPC Faction: Triglavian<br><i>&#8594; System effect:</i> C2 Wolf-Rayet<br>&#8594; <i>Former Jcode:</i> J174618"
    },
    25:{
        data_jbox_content:"<video class='vs' width='125' autoplay loop muted><source src='video/Shole.webm'></video>&#8594; <i>In addition to:</i> Porpoise and HIC<br>&#8594; <i>Jump size mass:</i> 5 000 000 kg<br>&#8594; <i>Regen per hour:</i> 3 000 000 000 kg<br>&#8594; <span class='small'>Frigate holes (S)</span>; 00 in each type"
    },
    26:{
        data_jbox_content:"<video class='vs' width='125' autoplay loop muted><source src='video/Mhole.webm'></video>&#8594; <i>In addition to:</i> DST and Nestor<br>&#8594; <i>Jump size mass:</i> 62 000 000 kg<br>&#8594; <span class='med'>Medium holes (M)</span>"
    },
    27:{
        data_jbox_content:"<video class='vs' width='125' autoplay loop muted><source src='video/Lhole.webm'></video>&#8594; <i>In addition to:</i> Orca<br>&#8594; <i>Jump size mass:</i> 375 000 000 kg<br>&#8594; <span class='large'>Large holes (L)</span>"
    },
    28:{
        data_jbox_content:"<video class='vs' width='125' autoplay loop muted><source src='video/xlhole.webm'></video>&#8594; <i>Jump size mass:</i> 1 000 000 000 kg<br>&#8594; <span class='xlarge'>Extra Large holes (XL)</span>"
    },
    29:{
        data_jbox_content:"<video class='vs' width='125' autoplay loop muted><source src='video/xlhole.webm'></video>&#8594; <i>Excluded:</i> Supercarrier and Titan<br>&#8594; <i>Jump size mass:</i> 2 000 000 000 kg<br>&#8594; <span class='xlarge'>Extra Large holes (XL)</span>"
    },
    30:{
        data_jbox_content:"&#8594; <i>Class:</i> C14<br>&#8594; NPC Faction: EDENCOM<br><i>&#8594; System effect:</i> C2 Red Giant<br>&#8594; <i>Former Jcode:</i> J055520"
    },
    31:{
        data_jbox_content:"<video width='125' autoplay loop muted><source src='video/c1.webm'></video>"
    },
    32:{
        data_jbox_content:"<video width='125' autoplay loop muted><source src='video/c2.webm'></video>"
    },
    33:{
        data_jbox_content:"<video width='125' autoplay loop muted><source src='video/c3.webm'></video>"
    },
    34:{
        data_jbox_content:"<video width='125' autoplay loop muted><source src='video/c4.webm'></video>"
    },
    35:{
        data_jbox_content:"<video width='125' autoplay loop muted><source src='video/c5.webm'></video>"
    },
    36:{
        data_jbox_content:"<video width='125' autoplay loop muted><source src='video/c6.webm'></video>"
    },
    37:{
        data_jbox_content:"<div class='tc'>Empire Space</div><br><span class='es'><video width='100' autoplay loop muted><source src='video/caldari.webm'></video><video width='100' autoplay loop muted><source src='video/amarr.webm'></video><br><video width='100' autoplay loop muted><source src='video/minmatar.webm'></video><video width='100' autoplay loop muted><source src='video/gallente.webm'></video></span>"
    },
    38:{
        data_jbox_content:"Each NS region reflects its own nebula on a wormhole."
    },
    39:{
        data_jbox_content:"<video width='125' autoplay loop muted><source src='video/pochven.webm'></video>"
    },
    40:{
        data_jbox_content:"<video width='125' autoplay loop muted><source src='video/thera.webm'></video>"
    },
    41:{
        data_jbox_content:"<video width='125' autoplay loop muted><source src='video/c13.webm'></video>"
    },
    42:{
        data_jbox_content:"ccp when ?"
    },
    43:{
        data_jbox_content:"Make sure to check visual cues and infotab for:<br>&#8594; wormhole size and destination<br>&#8594; wormhole mass and lifetime left"
    },
    44:{
        data_jbox_content:"K162 side behave as static, reappearing in its destination,<br>although it originates outside of it as wandering type.<br>&#8594; Known as <i>pseudo</i>, <i>reverse</i> or <i>K162 static</i>."
    },
    45:{
        data_jbox_content:"Class 7"
    },
    46:{
        data_jbox_content:"Class 8"
    },
    47:{
        data_jbox_content:"Class 9"
    },
    48:{
        data_jbox_content:"Class 25"
    },
    49:{
        data_jbox_content:"&#8594; Leads to <span class='ls'>Turnur</span> system"
    },
    50:{
        data_jbox_content:"&#8594; Rarely spawn in <span class='ns'>NullSec</span>"
    },
    51:{
        data_jbox_content:"&#8594; Leads to <span class='ls'>Tabbetzur</span> system"
    },
    52:{
        data_jbox_content:"&#8594; Is static in <span class='ls'>Turnur</span> and <span class='ls'>Tabbetzur</span> systems"
    },
    53:{
        data_jbox_content:"Sig level difference<br>&#8594; <i>Static:</i> I<br>&#8594; <i>Wandering:</i> II"
    },
    54:{
        data_jbox_content:"Sig level difference<br>&#8594; <i>Static:</i> II<br>&#8594; <i>Wandering:</i> I"
    },
    55:{
        data_jbox_content:"Sig level difference<br>&#8594; <i>Static:</i> III<br>&#8594; <i>Wandering:</i> II"
    },
}

let respawn={
    0:{  key:"static",      hover:"#79cef4", color:"#1d4145",         title:"Static", tooltip:""    },
    1:{  key:"wandering",      hover:"#79cef4", color:"#1d4145",         title:"Wandering",   tooltip:""  },
    2:{  key:"reverse",      hover:"#79cef4", color:"#1d4145",         title:"Reverse",   tooltip:tooltips[44]  },
}

let spawnIn={
    0:{   key:"class-1",     hover:"#42ffec", color:"#1d4145",  title:"Class 1", tooltip:tooltips[8]    },
    1:{   key:"class-2",     hover:"#42b3ff", color:"#1d4145",  title:"Class 2", tooltip:tooltips[9]    },
    2:{   key:"class-3",     hover:"#4265ff", color:"#1d4145",  title:"Class 3", tooltip:tooltips[10]    },
    3:{   key:"class-4",     hover:"#4230cf", color:"#1d4145",  title:"Class 4", tooltip:tooltips[11]    },
    4:{   key:"class-5",     hover:"#9c32ed", color:"#1d4145",  title:"Class 5", tooltip:tooltips[12]    },
    5:{   key:"class-6",     hover:"#f230dc", color:"#1d4145",  title:"Class 6", tooltip:tooltips[13]    },
    6:{   key:"highsec",     hover:"#0dfa05", color:"#1d4145",   title:"HighSec", tooltip:tooltips[45]    },
    7:{   key:"lowsec",     hover:"#f0a800", color:"#1d4145",  title:"LowSec", tooltip:tooltips[46]    },
    8:{   key:"nullsec",     hover:"#e81e1e", color:"#1d4145",  title:"NullSec", tooltip:tooltips[47]    },
    9:{   key:"class-12---thera",     hover:"#f6fc32", color:"#1d4145",  title:"Class 12 - Thera", tooltip:tooltips[14]    },
    10:{   key:"class-13---shattered",     hover:"#ffffff", color:"#1d4145",  title:"Class 13 - Shattered", tooltip:tooltips[15]      },
    11:{   key:"pochven-▲-trig-space",     hover:"#e81e1e", color:"#1d4145",  title:"Pochven ▲ Trig space", tooltip:tooltips[48]    },
    12:{   key:"",     hover:"#0dfa05", color:"#1d4145",   title:"", tooltip:""    },
    13:{   key:"drone-regions",     hover:"#e81e1e", color:"#1d4145",   title:"Drone Regions", tooltip:tooltips[16]    },
    14:{   key:"drifter-wormholes",     hover:"#79cef4", color:"#1d4145", title:"Drifter wormholes",tooltip:tooltips[17]   },
    15:{   key:"jove-observatories",     hover:"#79cef4", color:"#1d4145", title:"Jove Observatories",tooltip:tooltips[18]    },
    16:{   key:"",     hover:"#0dfa05", color:"#1d4145",   title:"", tooltip:""    },  
    17:{   key:"never-spawn",     hover:"#79cef4", color:"#1d4145", title:"never spawn",tooltip:tooltips[19]    },
    18:{   key:"",     hover:"#0dfa05", color:"#1d4145",   title:"", tooltip:""    },
    19:{  key:"exit",      hover:"#79cef4", color:"#1d4145", title:"EXIT",tooltip:tooltips[20]    },
}

let leadsTo={
    0:{    key:"c1",    hover:"#42ffec", color:"#1d4145",  title:"C1", tooltip:tooltips[31]    },
    1:{    key:"c2",    hover:"#42b3ff", color:"#1d4145",  title:"C2", tooltip:tooltips[32]    },
    2:{   key:"c3",    hover:"#4265ff", color:"#1d4145",  title:"C3", tooltip:tooltips[33]    },
    3:{    key:"c4",    hover:"#4230cf", color:"#1d4145",  title:"C4", tooltip:tooltips[34]    },
    4:{    key:"c5",    hover:"#9c32ed", color:"#1d4145",  title:"C5", tooltip:tooltips[35]    },
    5:{   key:"c6",     hover:"#f230dc", color:"#1d4145",  title:"C6", tooltip:tooltips[36]    },
    6:{   key:"hs",     hover:"#0dfa05", color:"#1d4145",   title:"HS", tooltip:tooltips[37]    },
    7:{   key:"ls",     hover:"#f0a800", color:"#1d4145",  title:"LS", tooltip:tooltips[37]    },
    8:{   key:"ns",     hover:"#e81e1e", color:"#1d4145",  title:"NS", tooltip:tooltips[38]    },
    9:{   key:"thera",     hover:"#f6fc32", color:"#1d4145",   title:"Thera", tooltip:tooltips[40]    },
    10:{   key:"c13",    hover:"#ffffff", color:"#1d4145",  title:"C13", tooltip:tooltips[41]    },
    11:{   key:"pochven",     hover:"#e81e1e", color:"#1d4145",  title:"Pochven", tooltip:tooltips[39]    },
    12:{   key:"",    hover:"#ffffff", color:"#1d4145",  title:"", tooltip:""    },  
    13:{   key:"sentinel-mz",     hover:"#79cef4", color:"#1d4145",  title:"Sentinel MZ", tooltip:tooltips[30]   },
    14:{   key:"liberated-barbican",     hover:"#79cef4", color:"#1d4145", title:"Liberated Barbican",tooltip:tooltips[21]    },
    15:{   key:"sanctified-vidette",     hover:"#79cef4", color:"#1d4145", title:"Sanctified Vidette",tooltip:tooltips[22]    },
    16:{    key:"conflux-eyrie",     hover:"#79cef4", color:"#1d4145", title:"Conflux Eyrie",tooltip:tooltips[23]   },
    17:{    key:"azdaja-redoubt",    hover:"#79cef4", color:"#1d4145", title:"Azdaja Redoubt",tooltip:tooltips[24]    },
    18:{   key:"",    hover:"#ffffff", color:"#1d4145",  title:"", tooltip:""    },
    19:{    key:"drifter-blackhole",    hover:"#79cef4", color:"#1d4145", title:"drifter blackhole",tooltip:tooltips[42]    },
    20:{    key:"jump-to-identify",    hover:"#79cef4", color:"#1d4145", title:"jump to identify",tooltip:tooltips[43]    },
} 
	
let indMass={
    0:{   key:"up-to-destroyer", hover:"#1f5eeb", color:"#1d4145",     title:"up to Destroyer",    tooltip:tooltips[25]},
    1:{  key:"up-to-battlecruiser",  hover:"#36cccc", color:"#1d4145",     title:"up to Battlecruiser",    tooltip:tooltips[26]},
    2:{  key:"up-to-battleship",  hover:"#d6d9cc", color:"#1d4145",     title:"up to Battleship",    tooltip:tooltips[27]},
    3:{  key:"up-to-freighter",  hover:"#d7601b", color:"#1d4145",     title:"up to Freighter",    tooltip:tooltips[28]},
    4:{   key:"up-to-capital", hover:"#d7601b", color:"#1d4145",     title:"up to Capital",    tooltip:tooltips[29]},
}

let toMass={
    0:{ key:"100-000-000-kg",   hover:"#79cef4", color:"#1d4145",     title:"100 000 000 kg",    tooltip:"" },
    1:{  key:"500-000-000-kg",  hover:"#79cef4", color:"#1d4145",     title:"500 000 000 kg",    tooltip:""},
    2:{  key:"750-000-000-kg",  hover:"#79cef4", color:"#1d4145",     title:"750 000 000 kg",    tooltip:""},
    3:{  key:"1-000-000-000-kg",  hover:"#79cef4", color:"#1d4145",     title:"1 000 000 000 kg",    tooltip:""},
    4:{  key:"2-000-000-000-kg",  hover:"#79cef4", color:"#1d4145",     title:"2 000 000 000 kg",    tooltip:""},
    5:{  key:"3-000-000-000-kg",  hover:"#79cef4", color:"#1d4145",     title:"3 000 000 000 kg",    tooltip:""},
    6:{  key:"3-300-000-000-kg",  hover:"#79cef4", color:"#1d4145",     title:"3 300 000 000 kg",    tooltip:""},
    7:{  key:"5-000-000-000-kg",  hover:"#79cef4", color:"#1d4145",     title:"5 000 000 000 kg",    tooltip:""},
}
let lifeTime={
    0:{  key:"4.5h",  hover:"#79cef4", color:"#1d4145",     title:"4.5h",    tooltip:""},	
    1:{  key:"12h",  hover:"#79cef4", color:"#1d4145",     title:"12h",    tooltip:""},
    2:{  key:"16h",  hover:"#79cef4", color:"#1d4145",     title:"16h",    tooltip:""},
    3:{  key:"24h",  hover:"#79cef4", color:"#1d4145",     title:"24h",    tooltip:""},
    4:{  key:"48h",  hover:"#79cef4", color:"#1d4145",     title:"48h",    tooltip:""},
}

let sigLevel={
    0:{  key:"i",  hover:"#79cef4", color:"#1d4145",     title:"I",    tooltip:""},
    1:{  key:"ii",  hover:"#79cef4", color:"#1d4145",     title:"II",    tooltip:""},
    2:{  key:"iii",  hover:"#79cef4", color:"#1d4145",     title:"III",    tooltip:""},
}

let wormholes={
    0:{
        name:'A009', hover:"yellow", color:"#1d4145", tooltip:tooltips[50], showincol:0,
        respawn:["wandering"],
        spawnIn:["class-1","class-2","class-3","class-4","class-5","class-6","class-12---thera","class-13---shattered","nullsec"],
        leadsTo:["c13"], 
        indMass:["up-to-destroyer"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["4.5h"],
        sigLevel:["i"],
    },
    1:{
        name:'A239', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["static"],
        spawnIn:["class-2",],
        leadsTo:["ls"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii"],
    },
    2:{
        name:'A641', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering"],
        spawnIn:["highsec",],
        leadsTo:["hs"], 
        indMass:["up-to-freighter"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i"],
    },
    3:{
        name:'A982', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering"],
        spawnIn:["class-3","class-12---thera"],
        leadsTo:["c6"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["iii"],
    },
    4:{
        name:'B041', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering"],
        spawnIn:["highsec",],
        leadsTo:["c6"], 
        indMass:["up-to-freighter"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["48h"],
        sigLevel:["iii"],
    },
    5:{
        name:'B274', hover:"yellow", color:"#1d4145", tooltip:tooltips[53], showincol:0,
        respawn:["static","wandering"],
        spawnIn:["class-2",],
        leadsTo:["hs"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i","ii"],
    },
    6:{
        name:'B449', hover:"yellow", color:"#1d4145", tooltip:tooltips[52], showincol:0,
        respawn:["wandering"],
        spawnIn:["lowsec","nullsec",],
        leadsTo:["hs"], 
        indMass:["up-to-freighter"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii","iii"],
    },
    7:{
        name:'B520', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering"],
        spawnIn:["class-6",],
        leadsTo:["hs"], 
        indMass:["up-to-freighter"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["48h"],
        sigLevel:["iii"],
    },
    8:{
        name:'B735', hover:"yellow", color:"#1d4145", tooltip:tooltips[0], showincol:0,
        respawn:["wandering"],
        spawnIn:["highsec","lowsec","nullsec","jove-observatories",],
        leadsTo:["liberated-barbican"], 
        indMass:["up-to-battleship"], 
        toMass:["750-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:[],
    },
    9:{
        name:'C008', hover:"yellow", color:"#1d4145", tooltip:tooltips[1], showincol:0,
        respawn:["wandering"],
        spawnIn:["class-1","class-2","class-3","class-4","class-5","class-6","class-12---thera","class-13---shattered",],
        leadsTo:["c5"], 
        indMass:["up-to-destroyer"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["4.5h"],
        sigLevel:["i"],
    },
    10:{
        name:'C125', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering"],
        spawnIn:["class-1"],
        leadsTo:["c2"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i"],
    },
    11:{
        name:'C140', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering"],
        spawnIn:["class-5","class-6"],
        leadsTo:["ls"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii"],
    },
    12:{
        name:'C247', hover:"yellow", color:"#1d4145", tooltip:tooltips[53], showincol:0,
        respawn:["static","wandering"],
        spawnIn:["class-4"],
        leadsTo:["c3"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii"],
    },
    13:{
        name:'C248', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering"],
        spawnIn:["class-6"],
        leadsTo:["ns"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i"],
    },
    14:{
        name:'C391', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering"],
        spawnIn:["class-6"],
        leadsTo:["ls"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["48h"],
        sigLevel:["ii"],
    },
    15:{
        name:'C414', hover:"yellow", color:"#1d4145", tooltip:tooltips[0], showincol:0,
        respawn:["wandering"],
        spawnIn:["highsec","lowsec","nullsec","jove-observatories",],
        leadsTo:["conflux-eyrie"], 
        indMass:["up-to-battleship"], 
        toMass:["750-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:[],
    },
    16:{
        name:'C729', hover:"yellow", color:"#1d4145", tooltip:tooltips[2], showincol:0,
        respawn:["wandering", "reverse"],
        spawnIn:["highsec","lowsec","nullsec","pochven-▲-trig-space"],
        leadsTo:["pochven"], 
        indMass:["up-to-freighter"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["12h"],
        sigLevel:["ii"],
    },
    17:{
        name:'D364', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["static"],
        spawnIn:["class-5",],
        leadsTo:["c2"], 
        indMass:["up-to-battleship"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["iii"],
    },
    18:{
        name:'D382', hover:"yellow", color:"#1d4145", tooltip:tooltips[53], showincol:0,
        respawn:["static","wandering"],
        spawnIn:["class-2","drifter-wormholes"],
        leadsTo:["c2"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii"],
    },
    19:{
        name:'D792', hover:"yellow", color:"#1d4145", tooltip:tooltips[3], showincol:0,
        respawn:["wandering"],
        spawnIn:["class-5","class-6"],
        leadsTo:["hs"], 
        indMass:["up-to-freighter"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["iii"],
    },
    20:{
        name:'D845', hover:"yellow", color:"#1d4145", tooltip:tooltips[4], showincol:0,
        respawn:["static"],
        spawnIn:["class-3"],
        leadsTo:["hs"], 
        indMass:["up-to-battleship"], 
        toMass:["5-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii"],
    },
    21:{
        name:'E004', hover:"yellow", color:"#1d4145",  tooltip:tooltips[1], showincol:0,
        respawn:["wandering"],
        spawnIn:["class-1","class-2","class-3","class-4","class-5","class-6","class-12---thera","class-13---shattered"], 
        leadsTo:["c1"], 
        indMass:["up-to-destroyer"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["4.5h"],
        sigLevel:["i"],
    },
     22:{
        name:'E175', hover:"yellow", color:"#1d4145", tooltip:tooltips[54], showincol:0,
        respawn:["static","wandering"],
        spawnIn:["class-5"],
        leadsTo:["c4"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii"],
    },
    23:{
        name:'E545', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["static"],
        spawnIn:["class-2"],
        leadsTo:["ns"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["iii"],
    },
    24:{
        name:'E587', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["static"],
        spawnIn:["class-12---thera"],
        leadsTo:["ns"], 
        indMass:["up-to-freighter"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    25:{
        name:'F135', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering", "reverse"],
        spawnIn:["class-2","class-3","class-4","class-5","class-6"],
        leadsTo:["thera"], 
        indMass:["up-to-battleship"], 
        toMass:["750-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    26:{
        name:'F216', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering", "reverse"],
        spawnIn:["class-2","class-3","class-4","class-5","class-6",],
        leadsTo:["pochven"], 
        indMass:["up-to-battleship"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    27:{
        name:'F353', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering", "reverse"],
        spawnIn:["class-1",],
        leadsTo:["thera"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["100-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    28:{
        name:'G008', hover:"yellow", color:"#1d4145", tooltip:tooltips[1], showincol:0,
        respawn:["wandering"],
        spawnIn:["class-1","class-2","class-3","class-4","class-5","class-6","class-12---thera","class-13---shattered"],
        leadsTo:["c6"], 
        indMass:["up-to-destroyer"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["4.5h"],
        sigLevel:["i"],
    },
    29:{
        name:'G024', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["static"],
        spawnIn:["class-6",],
        leadsTo:["c2"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["iii"],
    },
    30:{
        name:'H121', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        respawn:["wandering"],
        spawnIn:["class-1",],
        leadsTo:["c1"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["500-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i"],
    },
    31:{
        name:'H296', hover:"yellow", color:"#1d4145", tooltip:tooltips[53], showincol:0,
        respawn:["static","wandering"],
        spawnIn:["class-5",],
        leadsTo:["c5"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i","ii"],
    },
    32:{
        name:'H900', hover:"yellow", color:"#1d4145", tooltip:tooltips[55], showincol:0,
        respawn:["static","wandering"],
        spawnIn:["class-4",],
        leadsTo:["c5"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii","iii"],
    },
    33:{
        name:'I182', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-3","class-12---thera"],
        leadsTo:["c2"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    34:{
        name:'J244', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["static"],
        spawnIn:["class-1",],
        leadsTo:["ls"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii"],
    },
    35:{
        name:'J377', hover:"yellow", color:"#1d4145", tooltip:tooltips[49], showincol:0,
	    showincol:1,
        respawn:["wandering","reverse"],
        spawnIn:["class-1","class-2","class-3","class-4","class-12---thera"],
        leadsTo:["ls"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii"],
    },
    36:{
        name:'J492', hover:"yellow", color:"#1d4145", tooltip:tooltips[51], showincol:0,
	    showincol:1,
        respawn:["wandering","reverse"],
        spawnIn:["class-1","class-2","class-3","class-4"],
        leadsTo:["ls"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii"],
    },
    37:{
        name:'K329', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-4"],
        leadsTo:["ns"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["iii"],
    },
    38:{
        name:'K346', hover:"yellow", color:"#1d4145", tooltip:tooltips[5], showincol:0,
        showincol:1,
        respawn:["static"],
        spawnIn:["class-3"],
        leadsTo:["ns"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["iii"],
    },
    39:{
        name:'L005', hover:"yellow", color:"#1d4145",  tooltip:tooltips[1], showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-1","class-2","class-3","class-4","class-5","class-6","class-12---thera","class-13---shattered"],
        leadsTo:["c2"], 
        indMass:["up-to-destroyer"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["4.5h"],
        sigLevel:["i"],
    },
    40:{
        name:'L031', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering", "reverse"],
        spawnIn:["nullsec"],
        leadsTo:["thera"], 
        indMass:["up-to-freighter"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    41:{
        name:'L477', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["static"],
        spawnIn:["class-6"],
        leadsTo:["c3"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    42:{
        name:'L614', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-1","nullsec"],
        leadsTo:["c5",], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii","iii"],
    },
    43:{
        name:'M001', hover:"yellow", color:"#1d4145", tooltip:tooltips[1], showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-1","class-2","class-3","class-4","class-5","class-6","class-12---thera","class-13---shattered"],
        leadsTo:["c4"], 
        indMass:["up-to-destroyer"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["4.5h"],
        sigLevel:["i"],
    },
    44:{
        name:'M164', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering", "reverse"],
        spawnIn:["lowsec"],
        leadsTo:["thera"], 
        indMass:["up-to-freighter"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    45:{
        name:'M267', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["static"],
        spawnIn:["class-5"],
        leadsTo:["c3"], 
        indMass:["up-to-battleship"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    46:{
        name:'M555', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["highsec"],
        leadsTo:["c5"], 
        indMass:["up-to-freighter"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["iii"],
    },
    47:{
        name:'M609', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-1"],
        leadsTo:["c4"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    48:{
        name:'N062', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["static","wandering"],
        spawnIn:["class-2","drifter-wormholes"],
        leadsTo:["c5"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["iii"],
    },
    49:{
        name:'N110', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["static"],
        spawnIn:["class-1"],
        leadsTo:["hs"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i"],
    },
    50:{
        name:'N290', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-4"],
        leadsTo:["ls"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i"],
    },
    51:{
        name:'N432', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["lowsec","nullsec"],
        leadsTo:["c5"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i","iii"],
    },
    52:{
        name:'N766', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["static"],
        spawnIn:["class-4"],
        leadsTo:["c2"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    53:{
        name:'N770', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-3","class-12---thera"],
        leadsTo:["c5"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["iii"],
    },
    54:{
        name:'N944', hover:"yellow", color:"#1d4145", tooltip:tooltips[52], showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["lowsec","nullsec"],
        leadsTo:["ls"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i","ii"],
    },
    55:{
        name:'N968', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-3","class-12---thera"],
        leadsTo:["c3"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i"],
    },
    56:{
        name:'O128', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["highsec","lowsec","nullsec","never-spawn"],
        leadsTo:["c4"], 
        indMass:["up-to-battleship"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:[],
    },
    57:{
        name:'O477', hover:"yellow", color:"#1d4145", tooltip:tooltips[54], showincol:0,
        showincol:1,
        respawn:["static","wandering"],
        spawnIn:["class-2","drifter-wormholes"],
        leadsTo:["c3"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii"],
    },
    58:{
        name:'O883', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-1","nullsec"],
        leadsTo:["c3"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    59:{
        name:'P060', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["static"],
        spawnIn:["class-4"],
        leadsTo:["c1"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["500-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    60:{
        name:'Q003', hover:"yellow", color:"#1d4145", tooltip:tooltips[1], showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["class-1","class-2","class-3","class-4","class-5","class-6","class-12---thera","class-13---shattered"],
        leadsTo:["ns"], 
        indMass:["up-to-destroyer"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["4.5h"],
        sigLevel:["i"],
    },
    61:{
        name:'Q063', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["static"],
        spawnIn:["class-12---thera"],
        leadsTo:["hs"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["500-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    62:{
        name:'Q317', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["static"],
        spawnIn:["class-6"],
        leadsTo:["c1"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["500-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["iii"],
    },
    63:{
        name:'R051', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["highsec"],
        leadsTo:["ls"], 
        indMass:["up-to-freighter"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    64:{
        name:'R081', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["pochven-▲-trig-space"],
        leadsTo:["c4"], 
        indMass:["up-to-battleship"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    65:{
        name:'R259', hover:"yellow", color:"#1d4145", tooltip:tooltips[0], showincol:0,
        showincol:1,
        respawn:["wandering"],
        spawnIn:["highsec","lowsec","nullsec","jove-observatories"],
        leadsTo:["azdaja-redoubt"], 
        indMass:["up-to-battleship"], 
        toMass:["750-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:[],
    },
    66:{
        name:'R474', hover:"yellow", color:"#1d4145", tooltip:tooltips[55], showincol:0,
        showincol:2,
        respawn:["static","wandering"],
        spawnIn:["class-2","drifter-wormholes"],
        leadsTo:["c6"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii","iii"],
    },
    67:{
        name:'R943', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["highsec","lowsec","nullsec",],
        leadsTo:["c2"], 
        indMass:["up-to-battleship"], 
        toMass:["750-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii","iii"],
    },
    68:{
        name:'S047', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["class-4"],
        leadsTo:["hs"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii"],
    },
    69:{
        name:'S199', hover:"yellow", color:"#1d4145", tooltip:tooltips[52], showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["lowsec","nullsec"],
        leadsTo:["ns"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i","ii","iii"],
    },
    70:{
        name:'S804', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["class-1","nullsec"],
        leadsTo:["c6"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["iii"],
    },
    71:{
        name:'S877', hover:"yellow", color:"#1d4145", tooltip:tooltips[0], showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["highsec","lowsec","nullsec","jove-observatories"],
        leadsTo:["sentinel-mz"], 
        indMass:["up-to-battleship"], 
        toMass:["750-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:[],
    },
    72:{
        name:'T405', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["class-3","class-12---thera"],
        leadsTo:["c4"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i"],
    },
    73:{
        name:'T458', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering", "reverse"],
        spawnIn:["highsec"],
        leadsTo:["thera"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["500-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    74:{
        name:'U210', hover:"yellow", color:"#1d4145", tooltip:tooltips[6], showincol:0,
        showincol:2,
        respawn:["static"],
        spawnIn:["class-3"],
        leadsTo:["ls"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i"],
    },
    75:{
        name:'U319', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["lowsec","nullsec"],
        leadsTo:["c6"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["48h"],
        sigLevel:["i"],
    },
    76:{
        name:'U372', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering", "reverse"],
        spawnIn:["drone-regions"],
        leadsTo:["pochven"], 
        indMass:["up-to-battleship"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    77:{
        name:'U574', hover:"yellow", color:"#1d4145", tooltip:tooltips[55], showincol:0,
        showincol:2,
        respawn:["static","wandering"],
        spawnIn:["class-4"],
        leadsTo:["c6"], 
        indMass:["up-to-battleship"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["ii","iii"],
    },
    78:{
        name:'V283', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["highsec"],
        leadsTo:["ns"], 
        indMass:["up-to-freighter"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["iii"],
    },
    79:{
        name:'V301', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["class-3","class-12---thera"],
        leadsTo:["c1"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["500-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    80:{
        name:'V753', hover:"yellow", color:"#1d4145", tooltip:tooltips[53], showincol:0,
        showincol:2,
        respawn:["static","wandering"],
        spawnIn:["class-5"],
        leadsTo:["c6"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i","ii"],
    },
    81:{
        name:'V898', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["static"],
        spawnIn:["class-12---thera"],
        leadsTo:["ls"], 
        indMass:["up-to-freighter"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    82:{
        name:'V911', hover:"yellow", color:"#1d4145", tooltip:tooltips[53], showincol:0,
        showincol:2,
        respawn:["static","wandering"],
        spawnIn:["class-6"],
        leadsTo:["c5"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i","ii"],
    },
    83:{
        name:'V928', hover:"yellow", color:"#1d4145", tooltip:tooltips[0], showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["highsec","lowsec","nullsec","jove-observatories"],
        leadsTo:["sanctified-vidette"], 
        indMass:["up-to-battleship"], 
        toMass:["750-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:[],
    },
    84:{
        name:'W237', hover:"yellow", color:"#1d4145", tooltip:tooltips[53], showincol:0,
        showincol:2,
        respawn:["static","wandering"],
        spawnIn:["class-6"],
        leadsTo:["c6"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i","ii"],
    },
    85:{
        name:'X450', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["pochven-▲-trig-space"],
        leadsTo:["ns"], 
        indMass:["up-to-battleship"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["ii"],
    },
    86:{
        name:'X702', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["highsec","lowsec","nullsec"],
        leadsTo:["c3"], 
        indMass:["up-to-battleship"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["24h"],
        sigLevel:["i","ii"],
    },
    87:{
        name:'X877', hover:"yellow", color:"#1d4145", tooltip:tooltips[53], showincol:0,
        showincol:2,
        respawn:["static", "wandering"],
        spawnIn:["class-4"],
        leadsTo:["c4"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii"],
    },
    88:{
        name:'Y683', hover:"yellow", color:"#1d4145", tooltip:tooltips[54], showincol:0,
        showincol:2,
        respawn:["static","wandering"],
        spawnIn:["class-2","drifter-wormholes"],
        leadsTo:["c4"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii"],
    },
    89:{
        name:'Y790', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["static"],
        spawnIn:["class-5"],
        leadsTo:["c1"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["500-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["iii"],
    },
    90:{
        name:'Z006', hover:"yellow", color:"#1d4145", tooltip:tooltips[1], showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["class-1","class-2","class-3","class-4","class-5","class-6","class-12---thera","class-13---shattered"],
        leadsTo:["c3"], 
        indMass:["up-to-destroyer"], 
        toMass:["3-000-000-000-kg"], 
        lifeTime:["4.5h"],
        sigLevel:["i"],
    },
    91:{
        name:'Z060', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["static"],
        spawnIn:["class-1"],
        leadsTo:["ns"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["1-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["iii"],
    },
    92:{
        name:'Z142', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["class-5","class-6"],
        leadsTo:["ns"], 
        indMass:["up-to-capital"], 
        toMass:["3-300-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i"],
    },
    93:{
        name:'Z457', hover:"yellow", color:"#1d4145", tooltip:tooltips[54], showincol:0,
        showincol:2,
        respawn:["static","wandering"],
        spawnIn:["class-6"],
        leadsTo:["c4"], 
        indMass:["up-to-battleship"], 
        toMass:["2-000-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii"],
    },
    94:{
        name:'Z647', hover:"yellow", color:"#1d4145", tooltip:tooltips[53], showincol:0,
        showincol:2,
        respawn:["static","wandering"],
        spawnIn:["class-2","drifter-wormholes"],
        leadsTo:["c1"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["500-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii"],
    },   
    95:{
        name:'Z971', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:["wandering"],
        spawnIn:["highsec","lowsec","nullsec"],
        leadsTo:["c1"], 
        indMass:["up-to-battlecruiser"], 
        toMass:["100-000-000-kg"], 
        lifeTime:["16h"],
        sigLevel:["i","ii","iii"],
    },
    96:{
        name:'', hover:"yellow", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:[],
        spawnIn:[],
        leadsTo:[], 
        indMass:[], 
        toMass:[], 
        lifeTime:[],
        sigLevel:[],
    },
    97:{
        name:'⛮', hover:"black", color:"#1d4145", tooltip:"", showincol:0,
        showincol:2,
        respawn:[],
        spawnIn:[],
        leadsTo:["drifter-blackhole"], 
        indMass:[], 
        toMass:[], 
        lifeTime:[],
        misterBob:['bob'],
        sigLevel:[],
    },
    98:{
        name:'K162', hover:"yellow", color:"#1d4145", tooltip:tooltips[7], showincol:0,
        showincol:2,
        respawn:[],
        spawnIn:["exit"],
        leadsTo:["jump-to-identify"], 
        indMass:[], 
        toMass:[], 
        lifeTime:[],
        sigLevel:[],
    },
}
