// =============================================================================
// wormholes.js — Wormhole connection data
//
// Every wormhole that appears in the table is listed here.
// Fill in the fields to connect a wormhole to the filter columns.
// Leave arrays empty [] and values null to have no connections.
//
// spawn_in values: Class 1-6, HighSec, LowSec, NullSec,
//   Class 12 - Thera, Class 13 - Shattered, Pochven ▲ Trig space,
//   Drone Regions, Drifter wormholes, Jove Observatories, never spawn, EXIT
// leads_to values: C1-C6, HS, LS, NS, Thera, C13, Pochven,
//   Sentinel MZ, Liberated Barbican, Sanctified Vidette,
//   Conflux Eyrie, Azdaja Redoubt, drifter blackhole, jump to identify
// ship_size: up to Destroyer/Battlecruiser/Battleship/Freighter/Capital
// total_mass: 100/500/750 000 000 kg, 1/2/3/3.3/5 000 000 000 kg
// life_time: 4.5h, 12h, 16h, 24h, 48h
// sig_level: I, II, III
// =============================================================================

const WH_ENTRIES = [

  { wormhole:'A009', respawn:['Wandering'], spawn_in:['Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','NullSec','Class 12 - Thera','Class 13 - Shattered'], leads_to:['C13'], ship_size:'up to Destroyer', total_mass:'3 000 000 000 kg', life_time:'4.5h', sig_level:['I'] },
  { wormhole:'A239', respawn:['Static'], spawn_in:['Class 2'], leads_to:['LS'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'24h', sig_level:['II'] },
  { wormhole:'A641', respawn:['Wandering'], spawn_in:['HighSec'], leads_to:['HS'], ship_size:'up to Freighter', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I'] },
  { wormhole:'A982', respawn:['Wandering'], spawn_in:['Class 3','Class 12 - Thera'], leads_to:['C6'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['III'] },
  { wormhole:'B041', respawn:['Wandering'], spawn_in:['HighSec'], leads_to:['C6'], ship_size:'up to Freighter', total_mass:'3 000 000 000 kg', life_time:'48h', sig_level:['III'] },
  { wormhole:'B274', respawn:['Static','Wandering'], spawn_in:['Class 2'], leads_to:['HS'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'24h', sig_level:['I','II'] },
  { wormhole:'B449', respawn:['Wandering'], spawn_in:['LowSec','NullSec'], leads_to:['HS'], ship_size:'up to Freighter', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['II','III'] },
  { wormhole:'B520', respawn:['Wandering'], spawn_in:['Class 6'], leads_to:['HS'], ship_size:'up to Freighter', total_mass:'3 000 000 000 kg', life_time:'48h', sig_level:['III'] },
  { wormhole:'B735', respawn:['Wandering'], spawn_in:['HighSec','LowSec','NullSec','Jove Observatories'], leads_to:['Liberated Barbican'], ship_size:'up to Battleship', total_mass:'750 000 000 kg', life_time:'16h', sig_level:[] },
  { wormhole:'C008', respawn:['Wandering'], spawn_in:['Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','Class 12 - Thera','Class 13 - Shattered'], leads_to:['C5'], ship_size:'up to Destroyer', total_mass:'3 000 000 000 kg', life_time:'4.5h', sig_level:['I'] },
  { wormhole:'C125', respawn:['Wandering'], spawn_in:['Class 1'], leads_to:['C2'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'16h', sig_level:['I'] },
  { wormhole:'C140', respawn:['Wandering'], spawn_in:['Class 5','Class 6'], leads_to:['LS'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'24h', sig_level:['II'] },
  { wormhole:'C247', respawn:['Static','Wandering'], spawn_in:['Class 4'], leads_to:['C3'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I','II'] },
  { wormhole:'C248', respawn:['Wandering'], spawn_in:['Class 6'], leads_to:['NS'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'24h', sig_level:['I'] },
  { wormhole:'C391', respawn:['Wandering'], spawn_in:['Class 6'], leads_to:['LS'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'48h', sig_level:['II'] },
  { wormhole:'C414', respawn:['Wandering'], spawn_in:['HighSec','LowSec','NullSec','Jove Observatories'], leads_to:['Conflux Eyrie'], ship_size:'up to Battleship', total_mass:'750 000 000 kg', life_time:'16h', sig_level:[] },
  { wormhole:'C729', respawn:['Wandering','Reverse'], spawn_in:['HighSec','LowSec','NullSec','Pochven ▲ Trig space'], leads_to:['Pochven'], ship_size:'up to Freighter', total_mass:'1 000 000 000 kg', life_time:'12h', sig_level:['II'] },
  { wormhole:'D364', respawn:['Static'], spawn_in:['Class 5'], leads_to:['C2'], ship_size:'up to Battleship', total_mass:'1 000 000 000 kg', life_time:'16h', sig_level:['III'] },
  { wormhole:'D382', respawn:['Static','Wandering'], spawn_in:['Class 2','Drifter wormholes'], leads_to:['C2'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I','II'] },
  { wormhole:'D792', respawn:['Wandering'], spawn_in:['Class 5','Class 6'], leads_to:['HS'], ship_size:'up to Freighter', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['III'] },
  { wormhole:'D845', respawn:['Static'], spawn_in:['Class 3'], leads_to:['HS'], ship_size:'up to Battleship', total_mass:'5 000 000 000 kg', life_time:'24h', sig_level:['II'] },
  { wormhole:'E004', respawn:['Wandering'], spawn_in:['Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','Class 12 - Thera','Class 13 - Shattered'], leads_to:['C1'], ship_size:'up to Destroyer', total_mass:'3 000 000 000 kg', life_time:'4.5h', sig_level:['I'] },
  { wormhole:'E175', respawn:['Static','Wandering'], spawn_in:['Class 5'], leads_to:['C4'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I','II'] },
  { wormhole:'E545', respawn:['Static'], spawn_in:['Class 2'], leads_to:['NS'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['III'] },
  { wormhole:'E587', respawn:['Static'], spawn_in:['Class 12 - Thera'], leads_to:['NS'], ship_size:'up to Freighter', total_mass:'3 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'F135', respawn:['Wandering','Reverse'], spawn_in:['Class 2','Class 3','Class 4','Class 5','Class 6'], leads_to:['Thera'], ship_size:'up to Battleship', total_mass:'750 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'F216', respawn:['Wandering','Reverse'], spawn_in:['Class 2','Class 3','Class 4','Class 5','Class 6'], leads_to:['Pochven'], ship_size:'up to Battleship', total_mass:'1 000 000 000 kg', life_time:'12h', sig_level:['II'] },
  { wormhole:'F353', respawn:['Wandering','Reverse'], spawn_in:['Class 1'], leads_to:['Thera'], ship_size:'up to Battlecruiser', total_mass:'100 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'G008', respawn:['Wandering'], spawn_in:['Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','Class 12 - Thera','Class 13 - Shattered'], leads_to:['C6'], ship_size:'up to Destroyer', total_mass:'3 000 000 000 kg', life_time:'4.5h', sig_level:['I'] },
  { wormhole:'G024', respawn:['Static'], spawn_in:['Class 6'], leads_to:['C2'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['III'] },
  { wormhole:'H121', respawn:['Wandering'], spawn_in:['Class 1'], leads_to:['C1'], ship_size:'up to Battlecruiser', total_mass:'500 000 000 kg', life_time:'16h', sig_level:['I'] },
  { wormhole:'H296', respawn:['Static','Wandering'], spawn_in:['Class 5'], leads_to:['C5'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'24h', sig_level:['I','II'] },
  { wormhole:'H900', respawn:['Static','Wandering'], spawn_in:['Class 4'], leads_to:['C5'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['II','III'] },
  { wormhole:'I078', respawn:[], spawn_in:['Pochven ▲ Trig space'], leads_to:['Pochven'], ship_size:'up to Battlecruiser', total_mass:null, life_time:'4.5h', sig_level:[] },
  { wormhole:'I182', respawn:['Wandering'], spawn_in:['Class 3','Class 12 - Thera'], leads_to:['C2'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'J244', respawn:['Static'], spawn_in:['Class 1'], leads_to:['LS'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'24h', sig_level:['II'] },
  { wormhole:'J377', respawn:['Wandering','Reverse'], spawn_in:['Class 1','Class 2','Class 3','Class 4','Class 12 - Thera'], leads_to:['LS'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'24h', sig_level:['II'] },
  { wormhole:'J492', respawn:['Wandering','Reverse'], spawn_in:['Class 1','Class 2','Class 3','Class 4'], leads_to:['LS'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'24h', sig_level:['II'] },
  { wormhole:'K329', respawn:['Wandering'], spawn_in:['Class 4'], leads_to:['NS'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'16h', sig_level:['III'] },
  { wormhole:'K346', respawn:['Static'], spawn_in:['Class 3'], leads_to:['NS'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'16h', sig_level:['III'] },
  { wormhole:'L005', respawn:['Wandering'], spawn_in:['Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','Class 12 - Thera','Class 13 - Shattered'], leads_to:['C2'], ship_size:'up to Destroyer', total_mass:'3 000 000 000 kg', life_time:'4.5h', sig_level:['I'] },
  { wormhole:'L031', respawn:['Wandering','Reverse'], spawn_in:['NullSec'], leads_to:['Thera'], ship_size:'up to Freighter', total_mass:'3 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'L477', respawn:['Static'], spawn_in:['Class 6'], leads_to:['C3'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'L614', respawn:['Wandering'], spawn_in:['Class 1','NullSec'], leads_to:['C5'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'24h', sig_level:['II','III'] },
  { wormhole:'L687', respawn:[], spawn_in:['Pochven ▲ Trig space'], leads_to:['Pochven'], ship_size:'up to Battlecruiser', total_mass:null, life_time:'4.5h', sig_level:[] },
  { wormhole:'M001', respawn:['Wandering'], spawn_in:['Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','Class 12 - Thera','Class 13 - Shattered'], leads_to:['C4'], ship_size:'up to Destroyer', total_mass:'3 000 000 000 kg', life_time:'4.5h', sig_level:['I'] },
  { wormhole:'M164', respawn:['Wandering','Reverse'], spawn_in:['LowSec'], leads_to:['Thera'], ship_size:'up to Freighter', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'M267', respawn:['Static'], spawn_in:['Class 5'], leads_to:['C3'], ship_size:'up to Battleship', total_mass:'1 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'M555', respawn:['Wandering'], spawn_in:['HighSec'], leads_to:['C5'], ship_size:'up to Freighter', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['III'] },
  { wormhole:'M609', respawn:['Wandering'], spawn_in:['Class 1'], leads_to:['C4'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'N062', respawn:['Static','Wandering'], spawn_in:['Class 2','Drifter wormholes'], leads_to:['C5'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['III'] },
  { wormhole:'N110', respawn:['Static'], spawn_in:['Class 1'], leads_to:['HS'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'24h', sig_level:['I'] },
  { wormhole:'N290', respawn:['Wandering'], spawn_in:['Class 4'], leads_to:['LS'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['I'] },
  { wormhole:'N432', respawn:['Wandering'], spawn_in:['LowSec','NullSec'], leads_to:['C5'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'24h', sig_level:['I','III'] },
  { wormhole:'N766', respawn:['Static'], spawn_in:['Class 4'], leads_to:['C2'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'N770', respawn:['Wandering'], spawn_in:['Class 3','Class 12 - Thera'], leads_to:['C5'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['III'] },
  { wormhole:'N944', respawn:['Wandering'], spawn_in:['LowSec','NullSec'], leads_to:['LS'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'24h', sig_level:['I','II'] },
  { wormhole:'N968', respawn:['Wandering'], spawn_in:['Class 3','Class 12 - Thera'], leads_to:['C3'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I'] },
  { wormhole:'O128', respawn:[], spawn_in:['never spawn'], leads_to:[], ship_size:null, total_mass:null, life_time:null, sig_level:[] },
  { wormhole:'O477', respawn:['Static','Wandering'], spawn_in:['Class 2','Drifter wormholes'], leads_to:['C3'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I','II'] },
  { wormhole:'O546', respawn:[], spawn_in:['Pochven ▲ Trig space'], leads_to:['Pochven'], ship_size:'up to Battlecruiser', total_mass:null, life_time:'4.5h', sig_level:[] },
  { wormhole:'O883', respawn:['Wandering'], spawn_in:['Class 1','NullSec'], leads_to:['C3'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'P060', respawn:['Static'], spawn_in:['Class 4'], leads_to:['C1'], ship_size:'up to Battlecruiser', total_mass:'500 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'Q003', respawn:['Wandering'], spawn_in:['Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','Class 12 - Thera','Class 13 - Shattered'], leads_to:['NS'], ship_size:'up to Destroyer', total_mass:'3 000 000 000 kg', life_time:'4.5h', sig_level:['I'] },
  { wormhole:'Q063', respawn:['Static'], spawn_in:['Class 12 - Thera'], leads_to:['HS'], ship_size:'up to Battlecruiser', total_mass:'500 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'Q317', respawn:['Static'], spawn_in:['Class 6'], leads_to:['C1'], ship_size:'up to Battlecruiser', total_mass:'500 000 000 kg', life_time:'16h', sig_level:['III'] },
  { wormhole:'R051', respawn:['Wandering'], spawn_in:['HighSec'], leads_to:['LS'], ship_size:'up to Freighter', total_mass:'3 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'R081', respawn:['Wandering'], spawn_in:['Pochven ▲ Trig space'], leads_to:['C4'], ship_size:'up to Battleship', total_mass:'1 000 000 000 kg', life_time:'12h', sig_level:['II'] },
  { wormhole:'R259', respawn:['Wandering'], spawn_in:['HighSec','LowSec','NullSec','Jove Observatories'], leads_to:['Azdaja Redoubt'], ship_size:'up to Battleship', total_mass:'750 000 000 kg', life_time:'16h', sig_level:[] },
  { wormhole:'R474', respawn:['Static','Wandering'], spawn_in:['Class 2','Drifter wormholes'], leads_to:['C6'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['II','III'] },
  { wormhole:'R943', respawn:['Wandering'], spawn_in:['HighSec','LowSec','NullSec'], leads_to:['C2'], ship_size:'up to Battleship', total_mass:'750 000 000 kg', life_time:'16h', sig_level:['I','II','III'] },
  { wormhole:'S047', respawn:['Wandering'], spawn_in:['Class 4'], leads_to:['HS'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['II'] },
  { wormhole:'S199', respawn:['Wandering'], spawn_in:['LowSec','NullSec'], leads_to:['NS'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'24h', sig_level:['I','II','III'] },
  { wormhole:'S804', respawn:['Wandering'], spawn_in:['Class 1','NullSec'], leads_to:['C6'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'24h', sig_level:['III'] },
  { wormhole:'S877', respawn:['Wandering'], spawn_in:['HighSec','LowSec','NullSec','Jove Observatories'], leads_to:['Sentinel MZ'], ship_size:'up to Battleship', total_mass:'750 000 000 kg', life_time:'16h', sig_level:[] },
  { wormhole:'T405', respawn:['Wandering'], spawn_in:['Class 3','Class 12 - Thera'], leads_to:['C4'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I'] },
  { wormhole:'T458', respawn:['Wandering','Reverse'], spawn_in:['HighSec'], leads_to:['Thera'], ship_size:'up to Battlecruiser', total_mass:'500 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'U210', respawn:['Static'], spawn_in:['Class 3'], leads_to:['LS'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['I'] },
  { wormhole:'U319', respawn:['Wandering'], spawn_in:['LowSec','NullSec'], leads_to:['C6'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'48h', sig_level:['I'] },
  { wormhole:'U372', respawn:['Wandering','Reverse'], spawn_in:['Drone Regions'], leads_to:['Pochven'], ship_size:'up to Battleship', total_mass:'1 000 000 000 kg', life_time:'12h', sig_level:['II'] },
  { wormhole:'U574', respawn:['Static','Wandering'], spawn_in:['Class 4'], leads_to:['C6'], ship_size:'up to Battleship', total_mass:'3 000 000 000 kg', life_time:'24h', sig_level:['II','III'] },
  { wormhole:'V283', respawn:['Wandering'], spawn_in:['HighSec'], leads_to:['NS'], ship_size:'up to Freighter', total_mass:'3 000 000 000 kg', life_time:'16h', sig_level:['III'] },
  { wormhole:'V301', respawn:['Wandering'], spawn_in:['Class 3','Class 12 - Thera'], leads_to:['C1'], ship_size:'up to Battlecruiser', total_mass:'500 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'V753', respawn:['Static','Wandering'], spawn_in:['Class 5'], leads_to:['C6'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'24h', sig_level:['I','II'] },
  { wormhole:'V898', respawn:['Static'], spawn_in:['Class 12 - Thera'], leads_to:['LS'], ship_size:'up to Freighter', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['II'] },
  { wormhole:'V911', respawn:['Static','Wandering'], spawn_in:['Class 6'], leads_to:['C5'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'24h', sig_level:['I','II'] },
  { wormhole:'V928', respawn:['Wandering'], spawn_in:['HighSec','LowSec','NullSec','Jove Observatories'], leads_to:['Sanctified Vidette'], ship_size:'up to Battleship', total_mass:'750 000 000 kg', life_time:'16h', sig_level:[] },
  { wormhole:'W237', respawn:['Static','Wandering'], spawn_in:['Class 6'], leads_to:['C6'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'24h', sig_level:['I','II'] },
  { wormhole:'X450', respawn:['Wandering'], spawn_in:['Pochven ▲ Trig space'], leads_to:['NS'], ship_size:'up to Battleship', total_mass:'1 000 000 000 kg', life_time:'12h', sig_level:['II'] },
  { wormhole:'X702', respawn:['Wandering'], spawn_in:['HighSec','LowSec','NullSec'], leads_to:['C3'], ship_size:'up to Battleship', total_mass:'1 000 000 000 kg', life_time:'24h', sig_level:['I','II'] },
  { wormhole:'X877', respawn:['Static','Wandering'], spawn_in:['Class 4'], leads_to:['C4'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I','II'] },
  { wormhole:'Y683', respawn:['Static','Wandering'], spawn_in:['Class 2','Drifter wormholes'], leads_to:['C4'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I','II'] },
  { wormhole:'Y790', respawn:['Static'], spawn_in:['Class 5'], leads_to:['C1'], ship_size:'up to Battlecruiser', total_mass:'500 000 000 kg', life_time:'16h', sig_level:['III'] },
  { wormhole:'Z006', respawn:['Wandering'], spawn_in:['Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','Class 12 - Thera','Class 13 - Shattered'], leads_to:['C3'], ship_size:'up to Destroyer', total_mass:'3 000 000 000 kg', life_time:'4.5h', sig_level:['I'] },
  { wormhole:'Z060', respawn:['Static'], spawn_in:['Class 1'], leads_to:['NS'], ship_size:'up to Battlecruiser', total_mass:'1 000 000 000 kg', life_time:'16h', sig_level:['III'] },
  { wormhole:'Z142', respawn:['Wandering'], spawn_in:['Class 5','Class 6'], leads_to:['NS'], ship_size:'up to Capital', total_mass:'3 300 000 000 kg', life_time:'16h', sig_level:['I'] },
  { wormhole:'Z457', respawn:['Static','Wandering'], spawn_in:['Class 6'], leads_to:['C4'], ship_size:'up to Battleship', total_mass:'2 000 000 000 kg', life_time:'16h', sig_level:['I','II'] },
  { wormhole:'Z647', respawn:['Static','Wandering'], spawn_in:['Class 2','Drifter wormholes'], leads_to:['C1'], ship_size:'up to Battlecruiser', total_mass:'500 000 000 kg', life_time:'16h', sig_level:['I','II'] },
  { wormhole:'Z971', respawn:['Wandering'], spawn_in:['HighSec','LowSec','NullSec'], leads_to:['C1'], ship_size:'up to Battlecruiser', total_mass:'100 000 000 kg', life_time:'16h', sig_level:['I','II','III'] },

  // ⚙ — connects to drifter blackhole
  { wormhole:'GEAR', respawn:[], spawn_in:[], leads_to:['drifter blackhole'], ship_size:null, total_mass:null, life_time:null, sig_level:[] },

  { wormhole:'K162', respawn:[], spawn_in:['EXIT'], leads_to:['jump to identify'], ship_size:null, total_mass:null, life_time:null, sig_level:[] },

];
